### PR TITLE
Bolt-list missing class on bolt-list-item on web component

### PR DESCRIPTION
**Pull request by adamszalapski**
## Jira

http://vjira2:8080/browse/BDS-1157

## Summary

Update examples of web components by adding flex example and update web component `bolt-list-item` by adding behavior the same as in twig version.

## Details
Both versions must have the same HTML structure.

Twig version:
image

Web component version:
image

## How to test

Run this code locally and check if the web component version of display flex is the same as twig version by checking rendered HTML.

### CODE REVIEW

**Comment by adamszalapski** [comment]
@mikemai2awesome i remove all files from this PR except js file which fixing the issue.

**Comment by sghoweri** [comment]
whoa whoa whoa - hold on a sec. 

Why on earth are we externally adding component-specific CSS classes to these web components?

**Comment by adamszalapski** [comment]
@sghoweri without this fix flex don't be working as expected. I can add new css styles to `bolt-list-item` when a parent has a specific class. Please give me info if this approach will be better. I want to b consistent between twig and web component.

**Comment by adamszalapski** [comment]
@sghoweri i updated this PR to be working as a parent-child relation. Right now no class is added to `bolt-list-item` in twig or web component but correct behavior is in place.

**Pull request merged**
