### PR TITLE
Multiple Schema Per Component Support

### PR DESCRIPTION
**Pull request by joekarasek**
Alright, the guts of the schema have not been filled out (I'll leave that to Remy as the original author), but I have been able to test this and get validation errors to show up (see slack).

1) I'm not sure what we want to do re: the docs in PL for this.
2) The first item in the array in package.json for this setup needs to be the parent schema for the whole component. Sub-schema are then loaded into properties for that schema.

### CODE REVIEW

**Comment by rockymountainhigh1943** [comment]
This is actually pretty sweet! If we were to get this merged in, we could create another ticket down the line for showing multiple schema tables on the docs pages. I could see this being very useful.

**Comment by remydenton** [comment]
@sghoweri, I'm trying to resurrect this PR to finally get some forms schemas.  Looks like you added something like it in b2dfbdb, ("partial support for multiple schemas per component").  I can't seem to access schemas for multiple schemas using the same syntax Joe did in this initial PR though, and I don't see any examples of it working based on your work.  Any insight on why it was only "partial" in your commit?

**Comment by sghoweri** [comment]
> @sghoweri, I'm trying to resurrect this PR to finally get some forms schemas. Looks like you added something like it in [b2dfbdb](https://github.com/bolt-design-system/bolt/commit/b2dfbdb46cb8761b048e96c5169c8446b93d5560), ("partial support for multiple schemas per component"). I can't seem to access schemas for multiple schemas using the same syntax Joe did in this initial PR though, and I don't see any examples of it working based on your work. Any insight on why it was only "partial" in your commit?

@remydenton I’d have to dig into that but I think the issue was that the schema data wasn’t showing up in the global data we aggregate.

Regardless, I’m not convinced that multiple schemas per component are the best route for handling related components like forms. I feel like the UX and usability on the docs site would suffer if we tried to smoosh all these sub-component schemas together...

Any reason why we didn’t have each of these form inputs live as it’s own standalone component, all nested in a single folder?

**Comment by sghoweri** [comment]
Components generally shouldn't need to have more than 1 schema per package.

In the case of sub-components, we recommend either breaking the component down into smaller packages (each with it's own schema file) or to have the sub-component reference a section of the parent component's schema, such as what @danielamorse built for Accordion / Accordion Items: https://github.com/bolt-design-system/bolt/blob/master/packages/components/bolt-accordion/src/AccordionItem/accordion-item.twig#L9

**Pull request closed without merging**
