### PR TITLE
Border radius | Core | SCSS settings and tools

### PR DESCRIPTION
**Pull request by mikemai2awesome**
## Jira

http://vjira2:8080/browse/BDS-1108

## Summary

Added `bolt-border-radius()` scss function for better scalability and consistency.

## Details

1. Created border radius settings which contains the map with all available options, starting with the minimum of `small`, `large`, and `full`. This leaves room to scale if necessary in the future.
2. Created border radius tools which has the `bolt-border-radius()` scss function.
3. Did not change any existing components with border radius, that will come as separate tasks.

## How to test

Run the branch locally and create a dummy page, try to apply the `bolt-border-radius()` scss function in a dummy scss file to test all the available options.

### CODE REVIEW

**Comment by mikemai2awesome** [comment]
@danielamorse Yes, I left that open for scalability, but I don't believe it's necessary at the moment. Once we come to a scenario where we absolutely need something in between `small` and `large`, we can define it then.

**Comment by sghoweri** [comment]
> Once we come to a scenario where we absolutely need something in between `small` and `large`, we can define it then.

100% agree with this. No sense adding extra options that aren't getting used / needed currently. Most important thing is we have room to grow if / when the need arrises.

**Comment by sghoweri** [comment]
@mikemai2awesome @danielamorse I want to get this merged but food for thought: we should try to make it a habit to add corresponding utility classes (powered by the core settings / mixins we are building) whenever these net new things pop up. 

That way there's always feature parity between our lower level style options and the hight level utility classes.

**Comment by sghoweri** [comment]
^ @mikemai2awesome @danielamorse one of you guys want to create a ticket in the backlog to follow up with this?

**Comment by mikemai2awesome** [comment]
@sghoweri 

Added mixin and utils. Did not document utils yet, I can create a ticket for it.

**Pull request merged**
