### PR TITLE
Set up Docker deployment and Express Server

### PR DESCRIPTION
**Pull request by EvanLovely**
## Jira

- BDS-693
- BDS-586

## Summary

Replacing static site hosting with an Express server and a Docker deployment and wiring up the Bolt API!

## Details

Travis CI builds a Docker image that runs the install, build, and test and then pushes it up [to Docker Hub](https://cloud.docker.com/u/boltdesignsystem/repository/docker/boltdesignsystem/bolt), then our deploy script goes into the `./deploys/` folder to run the now.sh deploy that pulls that Docker image down to run and serve. This is done to get around issues that now's deploy script has with upload all the correct files due to it's incorrect parsing of ignore files. Additionally, all build dependencies like php, node, and yarn version are pre-built into the `bolt-docker` image (details on [Docker Hub](https://cloud.docker.com/u/boltdesignsystem/repository/docker/boltdesignsystem/bolt-docker) and the [GitHub repo](https://github.com/bolt-design-system/bolt-docker)).

Additionally, the route that was available at `/api` when running the local server is now hooked up to the hosted site! It's using the same routing so all should be available locally and on the deployed server.

I've also added the now.sh unique deploy urls as a commit status check to each commit so you can view the unique url each commit generated.

## How to test

All of this relates to CI work so checking Travis logs and its deployed site should be enough. However, one could build and run the Docker container using these commands:

```bash
bash ./scripts/docker-build.sh
bash ./scripts/docker-run.sh
```

To test the api, send a GET request to `/api` and you'll get back a simple response saying you've hit the Bolt API. The only other route that was being used locally, `/api/render-twig` is also available, but ensuring that it works on server as it does with a local server is outside the scope of this PR. 

## Remaining Work

- [x] Ensure redirects are in place:

https://github.com/bolt-design-system/bolt/blob/aebfb651e250e0fab1610662622b3b56b773ad33/Xnow.old.json#L8-L37

- [ ] Ensure that old deploys are not using the accounts finite amount of minimum [scaling](https://zeit.co/docs/api/v1/#endpoints/deployments/set-scale-configuration). I have the minimum set to 1 so the site loads quick. I could see setting old deploys that aren't the latest on a branch to a minimum scale of 0 so you could still access them but they didn't take up one of the "Instances" you have (pretty sure you're on [Pro plan with 25 available instances](https://zeit.co/pricing/v1)). Also, it's possible to clean up old deploys with:

```bash
now rm boltdesignsystem --safe --yes # --safe skips removing ones with active alias
```

- [x] Speed up CI. This looks like it's adding more time than I'd like.

- [ ] Consider how to handle NPM deps used in Deploy and Nightwatch scripts. I'm skipping the `yarn install` in the Travis build as the Docker build does that, so when our scripts that deploy and kick off Nightwatch testing start, they don't have. Currently I've set up the `./scripts` folders own `package.json` as a workaround:

https://github.com/bolt-design-system/bolt/blob/7d983c69d98caf2d3fc0623ce22bc8f18a598ebf/.travis.yml#L37-L40

### CODE REVIEW

**Comment by EvanLovely** [comment]
Say hello to your new API! https://feature-server.boltdesignsystem.com/api

**Comment by sghoweri** [comment]
Hoping to have a chance to start digging into this later today!

**Comment by EvanLovely** [comment]
@sghoweri How's this looking? Any questions I can answer?

**Comment by sghoweri** [comment]
Oh good @EvanLovely - was just about to ping you about now.sh’s status not returning back something to Github (pass, fail, timeout, etc) 😉

**Comment by sghoweri** [comment]
Taking another look at this now that #1008 has been approved and merged!

**Comment by sghoweri** [comment]
@EvanLovely @joekarasek 🥳
https://feature-server.boltdesignsystem.com/pattern-lab/?p=components-button-docs

df42bd87-5ff4-4a1c-ada6-2ac663f08302

**Comment by EvanLovely** [comment]
🎉 Awesome!! Happy New Year!

**Comment by sghoweri** [comment]
This should hopefully be good to merge in later today after a few small changes I’ll be wrapping up this morning:

1. Revert a few of the changes added in 
https://github.com/bolt-design-system/bolt/commit/35fb047b2703e6eaef9d87508c1cb234914d1421 — specifically the component schema changes made to the button and navbar components (other than then $ref update to wire up icons to the button) and revert adding Redux to this PR
2. Put in a Twig fix to remove the Drupal Attributes object from schemas being processed  
3. Put in a new PR wiring up Redux to our base web component Class
4. Nix the old Button component interactive demo
5. Separately add a few new tickets for the follow-up work with this: wiring up our remaining components to use the new Component Explorer, re-enabling local storage support to Redux, re-enabling the iframe resize functionality, ete!

**Pull request merged**
