### PR TITLE
Action Blocks | FE | Refactored props to follow conventions

### PR DESCRIPTION
**Pull request by mikemai2awesome**
## Jira

http://vjira2:8080/browse/BDS-1151
http://vjira2:8080/browse/BDS-1152

## Summary

Code cleanup on the action blocks component which includes refactoring props to follow Bolt's coding conventions.

## Details

1. Main twig file has been refactored to the latest format.
2. Set up each prop to validate against the schema.
3. Folder structure is re-organized to the latest format.
4. PL pages with action blocks includes have been updated to use new props.

## Deprecation

1. `maxItemsPerRow` has been renamed to `max_items_per_row`.
2. `align` has been updated to `valign` to clearly indicate vertical alignment.
3. `border` has been updated to `borderless` and its default set to `false`.

## How to test

Run the branch locally and check the following PL pages:

* Action blocks demo pages
* Full Page Theming pages
* D8 Homepage pages
* D8 Events pages

### CODE REVIEW

**Comment by mikemai2awesome** [comment]
@danielamorse 

I am not seeing the color bugs in IE11 or Edge. Can you tell me what version you are using?

Also, all the changes here are breaking changes. That's why I updated that. I can revert it if you think we should.

**Comment by danielamorse** [comment]
> I am not seeing the color bugs in IE11 or Edge. Can you tell me what version you are using?
> 
> Also, all the changes here are breaking changes. That's why I updated that. I can revert it if you think we should.

@mikemai2awesome never mind, I tested again and found it was a local env issue. Until you save a Twig file some of the SCSS is not there. I saved one, re-tested in IE11, and the colors were there.

Re: breaking changes, I don't know. It depends on how we plan to release these changes. If we marked this one private (like we are doing image and video) we can merge it and release with the next major release. How does that sound to you? Can/should it wait? cc @sghoweri

**Comment by danielamorse** [comment]
Update: discussed in standup and agreed this is safe to merge. No instances in bound. Waiting for tests to run then I will merge.

**Comment by sghoweri** [comment]
@mikemai2awesome @danielamorse @adamszalapski 

Out of curiosity, why was this refactored without having at least super basic testing coverage in place to ensure we didn't overlook anything OR accidentally wind up introducing a major breaking change?

**Comment by danielamorse** [comment]
> Out of curiosity, why was this refactored without having at least super basic testing coverage in place to ensure we didn't overlook anything OR accidentally wind up introducing a major breaking change?

On second thought, that's a good idea. It didn't occur to me when reviewing it. Should we make a ticket for that? @sghoweri

**Comment by adamszalapski** [comment]
It a good point maybe we must create for ou some review/testing steps that must occur.

**Comment by sghoweri** [comment]
> > Out of curiosity, why was this refactored without having at least super basic testing coverage in place to ensure we didn't overlook anything OR accidentally wind up introducing a major breaking change?
> 
> On second thought, that's a good idea. It didn't occur to me when reviewing it. Should we make a ticket for that? @sghoweri

I’m ok having tackle adding a couple basic tests separately (as a separate ticket) however ideally we’d have those tests created for the pre-refactored Action Blocks and then run the same tests against the updated version to make sure things are good to go.

I’m thinking perhaps we merge, mark as private, and create a new ticket to get a few tests in for this first before we publish the updates?

**Pull request merged**
