### PR TITLE
Auto-add Bolt Dependencies 

### PR DESCRIPTION
**Pull request by sghoweri**
## Jira
N/A

## Summary
Updates Bolt Build Tools to auto-add Bolt dependencies missing from the consumer’s `.boltrc` config file.

## Details
- Updates Bolt Build Tools to auto-add dependencies specified in the component's package.json file. 
- Adds snapshot component rendering testing for the `<bolt-image>` and `<bolt-video>` to verify `<bolt-ratio>` dependency specified is getting pulled in and compiled as expected.
- Relocates the `<bolt-ratio>` object to the components folder to help confirm auto-resolved and added deps are working as expected.
- Remaps existing `@bolt/global` references to the previous bolt ratio object to point at the new `@bolt/components-ratio` component location to avoid introducing a breaking change here.

## How to test
- Confirm `<bolt-image>` and `<bolt-video>` demos continue to work as expected
- Confirm Jest tests added render as expected

### CODE REVIEW

**Comment by sghoweri** [comment]
^ one other exciting thing about this is that we’re _super close_ to being able to create the component-specific CSS and JS on the fly which will pair quite nicely with the HTML we’re already generating...

CC @EvanLovely

**Comment by remydenton** [comment]
Jest tests are failing for me because we're using the twig function `random()` to generate video UUIDs, which results in this "failing" diff from Jest:
```diff
- <bolt-video  class="js-bolt-video-uuid--1489839513" data-setup="{&quot;techOrder&quot;: [&quot;Html5&quot;], &quot;resizeManager&quot;: false}" video-id="3861325118001" account-id="1900410236" show-meta player-id="r1CAdLzTW" controls v="2.1.6"></bolt-video>
+ <bolt-video  class="js-bolt-video-uuid--1039534106" data-setup="{&quot;techOrder&quot;: [&quot;Html5&quot;], &quot;resizeManager&quot;: false}" video-id="3861325118001" account-id="1900410236" show-meta player-id="r1CAdLzTW" controls v="2.1.6"></bolt-video>
```

**Comment by sghoweri** [comment]
> Since the ratio object is now deprecated, are there steps end users should take to prepare for its eventual removal? If so, write those out for use in the release notes.

@remydenton I think mentioning that the ratio object is now available as a separate standalone NPM install is important but no action is immediately required downstream since the ratio object was previously getting included automatically via the main `@bolt/global` package vs now it's getting included.

This PR actually makes that change not result in this being a major breaking change since we list out the ratio object as a dependency in the places that need to use it (and places where we need it in order for our Jest tests to run without any issues).

**Comment by sghoweri** [comment]
> Fix the failing Jest test

@remydenton all set -- anything left before we can OK this and merge? Need these updates for my video cue points work so we have some basic testing coverage in place

**Comment by sghoweri** [comment]
Thanks @remydenton!

I totally agree on the random UUID via the `test` env being slightly different behavior than what's expected in most situations however like you also mentioned, I figure this at least would help us start to figure out how best to handle dynamically generated / randomized data like this. Baby steps!

**Pull request merged**
