### PR TITLE
propagate breadcrumbs demo

### PR DESCRIPTION
**Pull request by joekarasek**
Breadcrumb component has been added to 1.x, including demonstrations in PL.

### CODE REVIEW

**Comment by joekarasek** [comment]
@sghoweri @EvanLovely I noticed that I accidently caught yarn.lock and composer.lock changes in this PR... Is that going to be a problem? Let me know and I will remove.

**Comment by sghoweri** [comment]
> @sghoweri @EvanLovely I noticed that I accidently caught yarn.lock and composer.lock changes in this PR... Is that going to be a problem? Let me know and I will remove.

I think it's probably fine - we can override that when this is getting merged in if we need to or if things conflict

**Comment by sghoweri** [comment]
@remydenton @mikemai2awesome could you guys chime in here? 

I'm a little out of the loop on the recent breadcrumbs work so you guys can better speak to if this looks like the updates we're expecting from v0.x on breadcrumbs, if we're missing anything, etc

**Comment by remydenton** [comment]
That all looks like the updates I'd expect, thanks @joekarasek

**Pull request merged**
