### PR TITLE
docs: Document Xdebug usage

### PR DESCRIPTION
**Pull request by remydenton**
## Jira

http://vjira2:8080/browse/BDS-1004

## Summary

Add documentation for setting up Xdebug to debug the PHP used when building Pattern Lab

## Details

I'm not sure if anyone else plans to use PHPStorm-- I started going into detail about it and then realized I might be the only one.  If so, I can flesh things out a bit more, especially in regards to finding your way around once you start debugging.

## How to test

Follow the steps at `/docs/guides/developer-tools/using-xdebug-for-PHP.html` and see if you can get debugging working.

### CODE REVIEW

**Comment by charginghawk** [comment]
@remydenton you might look into adding Twig breakpoint functionality to Bolt too. Something like:

https://packagist.org/packages/ajgl/breakpoint-twig-extension

(As used in my [singular Drupal claim to fame](https://www.drupal.org/project/twig_xdebug).)

**Comment by sghoweri** [comment]
> @remydenton you might look into adding Twig breakpoint functionality to Bolt too. Something like:
> 
> https://packagist.org/packages/ajgl/breakpoint-twig-extension
> 
> (As used in my [singular Drupal claim to fame](https://www.drupal.org/project/twig_xdebug).)

Neat!

**Comment by remydenton** [comment]
Interesting, thanks for the tip @charginghawk.  I've created http://vjira2:8080/browse/BDS-1017 to take a stab at that, but encourage reviewers to try following the PHP instructions in the meantime.

**Comment by sghoweri** [comment]
> For "Part II" and "Part III" I added instructions for VS Code, my editor of choice. Let me know if you have any suggestions for the formatting (or the content). I think the document is good semantically but our styles for the docs-site make it a little hard to scan, e.g. h2 and h3 are the same size, not enough space between sections.

Can we fix this? Ideally we can update the markdown processor to use Bolt components

**Comment by sghoweri** [comment]
Hey @remydenton @danielamorse is there still more work to be done on this (updates?) based on the Slack chat from late yesterday?

**Comment by remydenton** [comment]
Yes, I'd like to make a few more updates based on the convo yesterday @sghoweri.

Re: getting docs site headings working better, I 100% agree with both of you, but I think it's a non-trivial update.   Let's handle that as a separate ticket/PR.

**Comment by danielamorse** [comment]
@remydenton, good call on the reorganization. It's much easier to read now.

I updated the VS Code instructions with your "Build Pattern Lab" script. I was able to get it working locally using the same steps that I just added to the docs. It's pretty much the same code that you posted in your last screenshot. So, I'm not sure why it isn't working for you. Only thing I can think of is adding your bolt folder as a "Workspace" if you haven't already.

**Pull request merged**
