### PR TITLE
1st Round of PL Docs Polish

### PR DESCRIPTION
**Pull request by sghoweri**
Ok here's the TLDR version of this early 1st pass polishing up the Pattern Lab workshop for v1.0:

- Convert existing schema display over from a list to a table
- Adjust the data params getting passed into the schema display so the entire schema (not just the properties in the schema) gets passed along -- important since the `required` array of keys is missing otherwise
- Add 1st round of polish to the new schema table display: responsive layout, scrollable container, handle nested tables, etc
- Beginning work on PL docs layout (ex. edit in Github link, etc) via CSS Grid layout (WIP)!

### CODE REVIEW

**Comment by EvanLovely** [comment]
Wow; those tables looks great, nice job!! I really think this is the direction to go for these, I just want to make sure there's extra care taken when we're working with heavily nested and complex schemas. 

Here's an example on Action Blocks; comparing the old and new:

screenshot_2018-02-11_02-54-23_pm

screenshot_2018-02-11_02-54-04_pm

I don't think a table in a table is the right solution. I'm seeing a few scenarios that lead to this:

- Array of objects with string props
- Object in a object with string props

Also, a few other thoughts:

- [ ] Type should be it's own column; perhaps we can do some icons? Maybe it'd be simply "object `{}`", "string `abc`", "number `42`", "array `[]`"? Just an idea on the icon.
- [ ] All description start with `-` and a new line, let's remove that
- Many descriptions mention defaults and if it is required. I realize that's in the schema, so it's not for this PR, just calling it out. I don't think Jake or Joe knew of how to formally declare defaults or required when they were first going through it all.
- How about we put some data attributes in the schema template so it's easier to inspect and theme?
- Required could be removed as a column to save width and be either a red asterisks on the name, or the bg color could be a light red. I'm open to whatever, just a thought.
- I think hovering over the "Edit this page" should put a dotted outline (like Drupal Contextual Links) around the content we mean to edit, or we may get bug reports when people try to edit things above or below the markdown that is editable. PS I really like the icon!

screenshot_2018-02-11_03-05-48_pm

**Comment by sghoweri** [comment]
> Wow; those tables looks great, nice job!! I really think this is the direction to go for these, I just want to make sure there's extra care taken when we're working with heavily nested and complex schemas.

Thanks!! 100% agreed - just wanted to get a WIP version of this up first so we could chat about that after realizing there were a couple different scenarios with the deeply nested data that'd need to get ironed out.

Round 2 coming up!

**Comment by EvanLovely** [comment]
I wonder if we could have a different Twig `macro` for nested objects...

Also, @rockymountainhigh1943 should jump into this convo.

**Comment by sghoweri** [comment]
Or add an additional optional param to the macro (`nested`?) to specify that something needs to be rendered differently?

**Comment by rockymountainhigh1943** [comment]
These tables look AWESOME!! 👍 💯 🔥 

Jumping into the conversation here -- I really like the idea of breaking out more macros in the schema docs -- especially for cases like these. 

One possibly solution we should consider for items such as these would be to use a similar behavior as the icon reference here: https://5a7e2c30be40f14723ffce37--bolt-design-system.netlify.com/patterns/02-components-link-00-link-docs/02-components-link-00-link-docs.html

In our case for Action Blocks -- I think it would make sense to create a method to render arrays differently. So if the type is array:
1. We remove "Items:" and "Type: object" and move that up to where the description is so it would read "Type: `array` of `object`(s)"
1. We remove "Properties:" since we already know we're dealing with objects (which inherently have properties)
1. For simple items such as "text" and "url", we render as usual.
1. For more complex items like "icon" we utilize the `ref` attribute and render like the example for the link component above

This might be a good candidate to fully-bake the schema with `ref` attributes and see how the schema layout responds.

Let me know what you guys think when you have a sec. I'd be happy to work on busting this out if we decide its the best direction.

**Comment by joekarasek** [comment]
Check out this pattern. Can our docs handle this?
https://github.com/bolt-design-system/bolt/pull/431/files#diff-4953083abf1a8542e069b29d62151eb0

**Comment by EvanLovely** [comment]
> One possibly solution we should consider for items such as these would be to use a similar behavior as the icon reference here: https://5a7e2c30be40f14723ffce37--bolt-design-system.netlify.com/patterns/02-components-link-00-link-docs/02-components-link-00-link-docs.html

That ^^^ looks really awesome!! Though I do get worried when you apply a lot of scale to it.

I think what we should do is this:

1. If it's the top level object, apply these slick new tables
2. If it's anything below that, render using our current `ul>li>ul>li>ul` approach since that is very scalable.

I really want to get this to a decent looking place, then ship it - this'll be one of the easiest things to iterate on as it has nothing to do with Drupal themes or breaking API changes, and it has a single template and scss file. 

Remember our goals:

- What data do I need to pass in?
- What do the different properties do?
- What are my different options and how do they affect the output?
- What's the minimum I need to do to get this to work?

**Comment by sghoweri** [comment]
ok - think this is just about ready to merge in (minus the bunch of merge conflicts I'm now seeing - oi vey). 

I'd definitely like to add another layer of polish to this but with the top level table structure + nested list structure inside of this, I think we're pretty close... code wise at least, is there anything else (minus fixing that merge conflict - I'll fix that first thing tomorrow morning) we need to address before this 1st round can get merged down to epic/refactor?

**Comment by EvanLovely** [comment]
Something's weird with the git diff; like why is it showing that you're adding my `md-embed.twig` that was added in a different PR earlier today?

screenshot_2018-02-13_06-42-22_pm

**Comment by sghoweri** [comment]
^ the rest of the initial feedback on this still being part of the next iteration on this and still totally valid, just to be clear.

I think we're all 100% on the same page with wanting to get this buttoned up and polished - I just hate the idea of us holding off on merging something that's still a huge improvement for the whole team

**Comment by sghoweri** [comment]
> Something's weird with the git diff; like why is it showing that you're adding my md-embed.twig that was added in a different PR earlier today?

😱

**Comment by sghoweri** [comment]
Github acting up? Or is something messed up on my end?

I did do a squashed merge when pulling in the latest on epic/refactor earlier... 🤔

**Comment by EvanLovely** [comment]
I don't know, but it says "+1,923 −7,213" ....

**Comment by sghoweri** [comment]
@EvanLovely check again? Think I fixed it by re-merging in the latest

**Comment by EvanLovely** [comment]
- Let's remove the max width; the table has a lot of info and is overflowing for me. Also, since it's done with CSS Grid, how will it look on IE 11? That browser will head to these pages a lot for testing, so let's not give the impression of things looking broken.
- `Type` should be it's own column

**Comment by EvanLovely** [comment]
Still seeing this:

screenshot_2018-02-14_12-01-41_pm

**Pull request merged**
