### PR TITLE
Fix Drupal integration issues.

### LINKED ISSUE #189: Drupal doesn't support relative paths in Twig, breaks device-viewer.twig
https://github.com/bolt-design-system/bolt/blob/97d5bc9b62c9fb78ca5eee6bd4be8b82f76d8b65/src/_patterns/02-components/bolt-device-viewer/src/device-viewer.twig#L50

Drupal doesn't support this syntax. See:

https://drupal.stackexchange.com/questions/141066

Using the `@bolt` namespace works in Drupal, but I'm unable to check whether it breaks Bolt:

`{% include "@bolt/_screen-tilt.twig" %}`

### PR DESCRIPTION
**Pull request by charginghawk**
Resolves #189 #190

### CODE REVIEW

**Comment by sghoweri** [comment]
^ @charginghawk just waiting on the Travis build to finish before merging this in

**Comment by charginghawk** [comment]
Please hold off on merging until I can vouch for the Drupal integration. Right now it's still a little rough.

**Comment by sghoweri** [comment]
No worries - holding off for now till you give the word

**Comment by charginghawk** [comment]
Ready for this to merge on the Drupal side.

**Comment by sghoweri** [comment]
@charginghawk I've manually merged in these changes into my new product feature branch (needed a fresh clean branch to make merging back down to master a lot more straightforward) -- these changes are already there and will be part of the very next Bolt release being cut: https://github.com/bolt-design-system/bolt/blob/feature/product-page--fresh-branch/src/_patterns/02-components/bolt-device-viewer/src/device-viewer.twig#L52

**Pull request closed without merging**
