### PR TITLE
headline schema improvements

### PR DESCRIPTION
**Pull request by joekarasek**
This is pretty much done, but I want to talk about how Bolt is going to approach handling null in the schema. This one is sort of different than the others and I know we are shooting for consistent approaches across the code base.

### CODE REVIEW

**Comment by sghoweri** [comment]
@joekarasek given that I just merged in https://github.com/bolt-design-system/bolt/pull/522 which included updates to pull in and use the new (super handy) `remove_null` Twig filter, did you want to do another quick pass at this to add that in here or should I merge and we can follow-up with that after?

**Comment by remydenton** [comment]
This broke all kinds of things with headline styling.  

For example:
[Homepage demo before](https://5ab01488be40f15c951ca4bd--bolt-design-system.netlify.com/pattern-lab/patterns/04-pages-10-homepage--00-homepage/04-pages-10-homepage--00-homepage.html)
screen shot 2018-03-21 at 9 11 17 pm

[Homepage demo after](https://5ab14a1cefbe5d576246dbd7--bolt-design-system.netlify.com/pattern-lab/patterns/04-pages-10-homepage--00-homepage/04-pages-10-homepage--00-homepage.html)
screen shot 2018-03-21 at 9 11 09 pm

Hopefully there's a small and systematic fix?  In any case, it highlights the need for visual regression testing (automated of course, but human-powered until we get there, especially when refactoring core components like headline).

**Comment by sghoweri** [comment]
@remydenton @joekarasek  🤦‍♂️

I screwed up here. The original PR and Netlify URL appeared to have checked out but the subsequent one included the visual regression you mentioned @remydenton

On paper, this should be a non breaking minor update to shift the in-template validation over to use our YAML schema. I can't dig in for a couple hours but I'm guessing one or more of the values getting resolved here is different, causing the Headline to use the wrong tag, the wrong sub component... something along those lines.

**Comment by remydenton** [comment]
Thanks @sghoweri.  Good to hear it did check out during the initial review, so we shouldn't be that far off.

**Pull request merged**
