### PR TITLE
Modal Component

### PR DESCRIPTION
**Pull request by sghoweri**
## Jira

http://vjira2:8080/browse/BDS-48

## Summary

Create `bolt-modal` component to display dialogs for custom content.

## Details

- `bolt-modal` is available as a web component
- The component is dependent on javascript
- Modal Header and Footer regions only show when content is passed in
- Close button is auto-focused when modal opens
- Schema props are validated in the JS
- Same features work in IE11 and Edge
- Width, spacing, theme, and scroll area are customizable
- Persistent option is not available, this requires further work and considerations
- Image trigger (image zoom) can be created only with extra inline code
- Video modal (with play/pause control) can be created with additional JS
- Auto-open modal can be created with additional JS

## How to test

Run the branch locally, check all the demos, run tests to make sure they pass.

### CODE REVIEW

**Comment by mikemai2awesome** [comment]
@danielamorse No, we need to disable scrolling the background once a modal is activated.

**Comment by mikemai2awesome** [comment]
@adamszalapski Thanks!

The scrolling and video issues will have to be addressed by @danielamorse, since that involves JS. As for the image trigger, that's experimental, it's not how we intend to ship it, it's just an example of how you can hack it together for the time being.

We also decided to make modal dependent on JS from the beginning, so the 1st release will be JS only. More time is needed in the future to create the no-js fallback.

**Comment by danielamorse** [comment]
@adamszalapski, I fixed the following:
 - Modal background scroll
 - Modal video play/pause (moved to advanced configuration options page)

You may have to test locally. The build is still running.

@mikemai2awesome working on `bolt-trigger` next.

**Comment by mikemai2awesome** [comment]
@danielamorse Might need to namespace that, who knows what kind of js the drupal side is running and if they are using that name to do something else.

How about using a utility class like `u-bolt-overflow-hidden`? Since all we are doing is setting the overflow.

**Comment by charginghawk** [comment]
@mikemai2awesome Close!

```
$ grep -r noscroll docroot/modules/ docroot/themes/custom/pegawww_theme/src/ docroot/themes/custom/pegawww_theme/templates/
docroot/themes/custom/pegawww_theme/src//components/header/js/off-canvas-nav.es6.js:          noScroll: 'noscroll'
docroot/themes/custom/pegawww_theme/src//components/header/_components.mega-nav.mobile.scss:  .noscroll {
```

**Comment by sghoweri** [comment]
> @danielamorse Might need to namespace that, who knows what kind of js the drupal side is running and if they are using that name to do something else.
> 
> How about using a utility class like `u-bolt-overflow-hidden`? Since all we are doing is setting the overflow.

If that’s the only style we need to set, I’m good with this utility class approach!

**Comment by danielamorse** [comment]
> Need to pull in the trigger work to make the close button match the design. The work was done on the trigger branch.



> Need to pull in the trigger work to make the close button match the design. The work was done on the trigger branch.

@mikemai2awesome, trigger work has been pulled in. Ready for re-review: https://feature-modal.boltdesignsystem.com/pattern-lab/patterns/02-components-modal/index.html

**Comment by sghoweri** [comment]
> @sghoweri There's one outstanding todo for this: [159ff40#diff-f55ebcb122224a28748df4f3ab670403R157](https://github.com/bolt-design-system/bolt/commit/159ff4026cef908463675604a7df08cd83edc8fe#diff-f55ebcb122224a28748df4f3ab670403R157)
> 
> I don't think it's a blocker, tell me what you think.

@mikemai2awesome unless including this line of CSS is breaking something then agreed, I don’t think this would be a blocker we must address before merging this in. 👍🏼

**Pull request merged**
