### PR TITLE
Generic list component

### PR DESCRIPTION
**Pull request by mikemai2awesome**
## Jira

http://vjira2:8080/browse/BDS-548

## Summary

A flexible and customizable list component that can generate many different layouts.

## Details

screen shot 2018-08-20 at 5 59 53 pm

[View demo >](https://feature-bolt-list.bolt-design-system.com/pattern-lab/patterns/02-components-list/index.html)

This component aims to replace the following:

1. UI list
2. Block list
3. Inline list
4. Bare list

With the potential to build other components such as:

1. Breadcrumb
2. Pagination
3. Ordered list
4. Unordered list

This component also has the ability to transform its display. It can go from block to inline based on existing breakpoints within the design system.

## How to test

Pull down the branch and run locally. Inspect it visually in PL under `components > list`. Review the code in the List component folder.

### CODE REVIEW

**Comment by sghoweri** [comment]
Very nice work @mikemai2awesome! Starting to review this now — have a couple small things to chat about however I’m loving what I’m seeing so far. 💯

**Comment by mikemai2awesome** [comment]
@sghoweri Thanks!

I will work on the suggestions and questions. As for comment (2), based on our discussion, that's the actual intended effect. Top align should actually be top align optically when two things are put side by side. The current ui list lining up with the big headline is just a coincidence.

**Comment by mikemai2awesome** [comment]
# Progress
@sghoweri @remydenton Here's what I've covered in my latest push.

## Overall Observations
- [x] 1. Breadcrumbs can be built differently if `bolt-list` is available. It would be an inline `bolt-list` with xsmall spacing and no separators. A breadcrumb item (which would include the link and the special separator) should be passed as an item for the `bolt-list`.
- [x] 2. As discussed, true alignment is the intended effect.

## Suggestions
- [x] Tag prop added.
- [x] `hr` removed, CSS updated.
- [x] I believe all spacing values should be available, the larger options might look too big in general for block display (inline display looks reasonable), but we are not building the layouts, we are simply providing the tools to accommodate different scenarios. The values are defined by the design system and should be expected.
- [x] Just like the spacing values, breakpoints are defined by the design system and should be expected, however, I am ok with taking out all large breakpoints from the schema for now until the need rises since the point of this feature is to accommodate smaller screens.
- [x] It should be added to the `package.json` file.

## Questions
- [x] `valign` is very useful when building an inline list of items with different heights (ie. a list of sponsor logos).
- [x] I believe we should provide two most basic border styles to give design some freedom. That being said, I can see that dotted is not very distinctly different than solid. So I have changed it to dashed. Regardless, separator shouldn't be a boolean so it's future-proof.
- [x] My idea of rebuilding the action blocks is to create specific styles and spacing for a single action block, and pass that as an item to an inline `bolt-list`. This would be similar to how I would rebuild breadcrumbs.
- [x] Not too warm on this idea yet, since the Drupal team essentially create their own patterns. Our pattern library would get outdated really quickly if there's not a way to sync up with what the Drupal team creates. Also, how consumers decide to configure and combine our components should not be part of what we ship. I am more for the idea of showing them examples of what they are trying to accomplish and they have to keep their own pattern library up to date (with their own naming conventions and standards).

## Next steps
- [x] It is magically passing travis now. I do not know what I fixed...
- [x] When we actually run through replacing those components, I would do the testing then and create more demo pages. I believe all the props are in place to make that happen. The current demos do cover the following: ui-list, inline-list, chip-list, button-group.
- [ ] I need directions as to how to convert this to a web component.

**Comment by remydenton** [comment]
I still think breadcrumb could be built by just adding a special separator to this component (and deprecating the breadcrumb component entirely).  That's a question for when we update breadcrumb though.  I'm on board with everything else here.

**Comment by mikemai2awesome** [comment]
@remydenton In theory, it can replicate the current breadcrumb, but the current one isn't using the chevron icon from the system. Consistency wise this is not great, you can notice they don't look exactly the same because one is pure CSS and one is bolt-icon. If we rebuild breadcrumb with an icon from the system, it complicates the markup, and breadcrumb specific CSS would be needed to achieve it.

**Comment by remydenton** [comment]
As discussed with @mikemai2awesome, I'm going to go ahead and merge since this is a) stable (all feedback that affects stability has been addressed) and b) blocking other work like #848.  @sghoweri, feel free to add additional thoughts here so we can discuss and/or roll them into a follow up ticket.

**Pull request merged**
