### PR TITLE
Bolt-Pagination Component

### PR DESCRIPTION
**Pull request by rockymountainhigh1943**
This PR contains everything needed for the initial build out of the new `bolt-pagination` component and includes twig-only implementation, schema, docs, demos, and full styling integrated with themes.

The idea behind the implementation is pretty simple and should be able to fit a wide variety of pagination configurations by simply passings in the `total` pages, `current` page, and `pager` (e.g. "/pages/" for a structure like "domain.com/pages/5") params.

### CODE REVIEW

**Comment by remydenton** [comment]
@rockymountainhigh1943, this is an excellent first pass!  Your examples in pattern lab are particularly good and do a great job of balancing minimal redundancy with clarity.  I also like the simplicity of no javascript here.

Two broad categories that I think we should cover in code review and iterate on (bullet points are potential improvements I see off-hand):
## CSS
  1. Targeting classes instead of elements with CSS styles
  2. Full integration with the theming/color system

## Schema and miscellaneous twig
  1. Updating schema to allow for a backend that has already handled a lot of the logic for which pages to show and what the links should be.
  2. Accessibility (minor)
  3. Translatability (minor)

---------
I'm going to leave the CSS part to @mikemai2awesome to review since it's his specialty.  @sghoweri might also have advice on the theming system.  My review will focus on schema, which I see as the biggest thing to get right at this stage (hard to change later on) and the other misc. stuff in Twig.  Stay tuned!

**Comment by sghoweri** [comment]
+1 really great first pass here — nice work!

Really would love to see us also tighten up the CSS selectors to purely use BEM classes. We should really do everything we can to avoid using element selectors in everything but the rarest of situations.

**Comment by rockymountainhigh1943** [comment]
@remydenton - nice work on your assessment and the updates pushed!

I think this looks great and I'll wait to see what @mikemai2awesome has to add on the CSS items. I did run through the theme integration with Mike previously, however, if there is a more up-to-date approach for this I would love to learn it!

Thanks guys!

**Comment by remydenton** [comment]
Glad to hear, thanks for reviewing @rockymountainhigh1943.

The theme integration may be fine actually-- I admit to not fully understanding all the best practices myself, and I know Salem is reworking some of the theming stuff anyway right now.

The part @sghoweri's comment references is just the BEM style classes, which I agree we should update (though that could be a follow-up task after merging).  Here's my favorite resource for that: https://css-tricks.com/bem-101/.  You're already using elements of it with a few exceptions:

- Avoid nested selectors like `.c-bolt-pagintation li`
- Instead, add classes to all elements and keep your CSS selectors flat:

```html
<li class="c-bolt-pagination__item">
  <a class="c-bolt-pagination__link"></a>
</li>
```
```css
.c-bolt-pagination__item { ... }
.c-bolt-pagination__link { ... }
```
- Take care about the difference between an element and a modifier.
```css
.c-bolt-pagination__item {}
.c-bolt-pagination__item--next {}
```
Probably best to work with @mikemai2awesome on the details-- let me know if you feel like there's anything to work on today or we should go ahead and merge now and move that to follow-on tickets.

**Comment by remydenton** [comment]
Closing this in favor of #787, which includes all this work as well as additional updates from Mike.

**Pull request closed without merging**
