### PR TITLE
Sticky | Docs | Testing and documentation for sticky components

### PR DESCRIPTION
**Pull request by TashaBasalt**
## Jira

http://vjira2:8080/browse/BDS-944

## Summary

Adding jest tests

## Details

Adding Jest snapshot tests and TESTING.md file

## How to test

yarn test:js

### CODE REVIEW

**Comment by TashaBasalt** [comment]
@mikemai2awesome Could you direct me to an example of a functional Jest test in the code base to show me what you mean? I've only seen Snapshots thus far.

**Comment by mikemai2awesome** [comment]
@TashaBasalt Hi there. I do not know of an example, you will need to create one from scratch. Can @joekarasek consult on this?

**Comment by joekarasek** [comment]
@mikemai2awesome @sghoweri  I was able to add a simple functional test around the sticky behavior. Nightwatch will use the first sticky example "simple", will scroll to the bottom of the page, then get the bounding box for the first sticky element and confirm that its top = 0. I broke the sticky element (removed the polyfill, removed the position:sticky) and confirmed that this test fails when its not working. Does this sound good to you?

**Comment by sghoweri** [comment]
Looks like the Nightwatch test for this is failing in Firefox, likely related to https://bugzilla.mozilla.org/show_bug.cgi?id=1518376#c2

I'm going to get this merged down to master + test updating the Nightwatch + Firefox versions to see if that resolves the issue

**Pull request merged**
