### PR TITLE
Implement SassDoc

### PR DESCRIPTION
**Pull request by rockymountainhigh1943**
## Jira

http://vjira2:8080/browse/BDS-518

## Summary

Implements all comment documentation for SassDoc

## Details

Previously before this PR, we had undocumented variables, mixins, and functions. The work contained within this branch completes the first round documentation of those missing items.

## How to test

1. Pull down the branch and run `npm run sassdoc:build` at the root of the project
1. Change directories into `/apps/pattern-lab` and run `npm run start`
1. When PL opens, navigate to Styleguide-->Sassdoc

### CODE REVIEW

**Comment by mikemai2awesome** [comment]
@rockymountainhigh1943 

I could not get `npm run sassdoc:build` to work. Is there something else I need to do? Sassdoc command is not found.

**Comment by rockymountainhigh1943** [comment]
@remydenton – would you be willing to review this and merge if it's all set?

**Comment by sghoweri** [comment]
@remydenton @rockymountainhigh1943 @mikemai2awesome this is good to merge down to master as soon as I get the OK from the Travis build currently running. I've also added in a few things so this compiles out consistently whenever our Webpack build runs, automatically -- no more npm script required.

Nice job guys!!

**Comment by remydenton** [comment]
@sghoweri, I just added this to our 1.x release notes for you #840.  Please make sure to do that step whenever you merge a PR into master.

**Comment by sghoweri** [comment]
Thanks @remydenton! Gah — sorry. I didn’t forget about this one, I swear! 😅

**Pull request merged**
