### PR TITLE
Feature/twig approach

### PR DESCRIPTION
**Pull request by EvanLovely**
This cleans up nearly all of the Twig files that weren't able to be included - you know; when you try to include a file and all PL does is spit out `@bolt/my-thing.twig` in the rendered HTML and gives no errors. Compare by searching for `@bolt` after selecting "View Source" in browser of the View All page:

- 239 results on `epic/refactor` - [View All page](https://5a66aafe8198760e316828ef.bolt-design-system.netlify.com/styleguide/html/styleguide.html)
- 0 results on this branch - [View All page](https://5a6a6f730b79b7503890f8d5.bolt-design-system.netlify.com/styleguide/html/styleguide.html)

So here's a summary of what's done:

- We no longer need `twig` in `package.json` at all; if a component is added to `boltrc`, then it's folder and all sub-folder in it can be accessed via `@bolt` or it's own namespace: if package name was `@bolt/components-page-footer` it gets a namespace of `@bolt-components-page-footer` so you could `{% include "@bolt-components-page-footer/page-footer.twig" %}`
- Changing `plTwigNamespaces` config option to `twigNamespaces`
- Updating these components to use new compile method:
    - `@bolt/components-device-viewer`
    - `@bolt/components-icon`
    - `@bolt/components-icons`
- Replacing `@bolt/paragraph.twig` with just a `<p>` - cause that's all the old one did
- Stubbing in [temp static data for getting `boltSpacingSizes` into JS](https://github.com/bolt-design-system/bolt/blob/feature/twig-approach/packages/core/data/spacing-sizes.js) for now since icons needs that data.
- Adjusting page-footer so Lerna picks it up right
- Adding missing page-header.twig file from 0.x

---

Now, this doesn't fix everything, there's some files that are using the `pattern_template` custom Twig function (ie `{% include pattern_template('teaser') %}`) - the good news is I've narrowed it down to only these:

```
button_group - @bolt-button-group/button-group.twig
card - @bolt-card/card.twig
eyebrow - @bolt-headline/eyebrow.twig
flag - @bolt-global/flag.twig
headline - @bolt-headline/headline.twig
image - @bolt-global/image.twig
teaser - @bolt-teaser/teaser.twig
text - @bolt-headline/text.twig
video - @bolt-video/video.twig
```

I plan on that being in another PR; but just wanted to call it out now. For now, you'll see the word "card" instead of a Card rendered.

### CODE REVIEW

**Comment by EvanLovely** [comment]
Relates to:

- [Update components to compile using new build tools · Issue #309 · bolt-design-system/bolt](https://github.com/bolt-design-system/bolt/issues/309)
- [update js packages by remydenton · Pull Request #346 · bolt-design-system/bolt](https://github.com/bolt-design-system/bolt/pull/346)
- [update icons component DO NOT MERGE (needs work) by remydenton · Pull Request #344 · bolt-design-system/bolt](https://github.com/bolt-design-system/bolt/pull/344)

**Comment by EvanLovely** [comment]
If requested, I'd be happy to refactor this so it does not include updating the components to the new compile method as we have some other PRs in place for that already and may want to discuss the specific implementations there. I just kept at it until the View Source of the View All had no search results for `@bolt`

**Comment by remydenton** [comment]
I closed PR #344 in favor of this and merged the base branch back into PR #346 to resolve conflict.  I'm happy to resolve conflicts for #346 again if we want to merge this in first.

**Comment by EvanLovely** [comment]
I think we should merge in #346 first

**Comment by EvanLovely** [comment]
Just merged it in

**Pull request merged**
