### PR TITLE
Small Tweaks to Speed Bump PR (+ Perf Boost?)

### PR DESCRIPTION
**Pull request by sghoweri**
Testing out a few small tweaks to #216 
1. Updates our existing Image component to use a pre-optimized image asset when calculating the color / base64 placeholder.
2. Removes ColorThief from bgcolor Twig extension and replaces it with a much lighter weight (albeit, probably a tad less precise) calculation
3. Removed the `export` from the npm script setting the environmental variable to test how that affects the Travis build

Out of curiosity @EvanLovely - could you test running the full build of this on your end and report back on the perf hit you're getting?

Locally I'm seeing much better compile times with everything switched on (even after wiping the local image cache) so I'm curious how well this runs on your end -- lmk!

**Cold cache:**
site generation took 15.565734863281 seconds and used 166MB of memory...

**With cache:**
site generation took 14.022073984146 seconds and used 162MB of memory...

**Disabled:**
site generation took 13.839860916138 seconds and used 162MB of memory...

### CODE REVIEW

**Comment by sghoweri** [comment]
@EvanLovely thoughts on getting this folded into your original PR before we get all this merged into master?

**Comment by EvanLovely** [comment]
@sghoweri Looks good! I added 46b5174 since the prod conditional was inverted. I'm seeing these time results currently:

```bash
time php core/console --generate
site generation took 31.538532018661 seconds and used 158MB of memory...
29.97s user 1.13s system 98% cpu 31.618 total
```

And with prod switch:

```bash
time NODE_ENV=production php core/console --generate
site generation took 31.36253619194 seconds and used 158MB of memory...
29.78s user 1.16s system 98% cpu 31.442 total
```

So.... the `bgcolor` function in this new format doesn't even effect build times by a second?? Part of me is elated and another part of me is confused to the point that I worry something's off...

Also, looks like the CI build is failing now that the prod conditional is corrected. What happened?

**Comment by sghoweri** [comment]
@EvanLovely looks like Travis isn't currently configured to use Imagick?

Fatal error: Uncaught Error: Class 'Imagick' not found in /home/travis/build/bolt-design-system/bolt/packages/bolt-twig-extensions/functions/custom-functions/responsive-images/bgcolor.function.php:55

**Comment by charginghawk** [comment]
Good to see some improvement on bgcolor's historical performance issues. I think in terms of Drupal integration, we'd prefer it to be optimized with some kind of caching, or even just calculate it on image save on the Drupal side and pass it in as a field.

**Pull request closed without merging**
