### PR TITLE
Allow caller to provide weight override to headline component.

### PR DESCRIPTION
**Pull request by krlucas**

### CODE REVIEW

**Comment by sghoweri** [comment]
@mikemai2awesome @remydenton you guys ok with this?

After chatting with @krlucas yesterday about the need to give content authors the ability to customize the font weight of arbitrary words inside a headline (ex. "My awesome text <strong>can sometimes be bolder</strong>"), we felt like this would be the most straightforward way to get us there without us requiring to add a brand new headline-like component (there's already more than enough -- even too many) or to do something crazy like pretending like the user is choosing to use a Headline component but secretly using a Subheadline template instead...

Thoughts?

**Comment by sghoweri** [comment]
FYI here's what this headline update would allow for (default text can use the lighter weight with a bolder weight around whatever else the user wants):
06ac3cbe-d19d-436e-b533-a4912cf189ed

**Comment by sghoweri** [comment]
One other thing @mikemai2awesome - we'll need to make sure the Headline component's inner vertical alignment gets updated to be handled via display: inline-block vs display: inline-flex like it is currently.

Looks like the flex-based layout for this (when additional inline tags like <strong> get used) breaks quite a bit... At the moment Drupal is outputting an extra <div> around the headline text content getting output which temporarily works around the issue however we really should just get the CSS for this updated so the Drupal markup can match up 1:1

**Comment by mikemai2awesome** [comment]
The alignment issue might be a result of outdated headline and/or text component. No flex display is set on `c-bolt-text__text` or `c-bolt-headline__text`.

**Pull request merged**
