### PR TITLE
Epic: Micro Journeys, Animate, Editor

### PR DESCRIPTION
**Pull request by joekarasek**
# 🚧 Work In Progress 🚧

Interactive Pathways, built on Web components.

These are the final NPM packages that will be added by us:

- `@bolt/animations` Visual Styles for animations
- `@bolt/animate` Web Component that animates children
- `@bolt/editor` Editor template (it will have Twig template) and JS app
- `@bolt/micro-journeys` Collection of multiple Web Components that are highly animatable

### CODE REVIEW

**Comment by margoromo** [comment]
Added http://vjira2:8080/browse/BDS-1718 and http://vjira2:8080/browse/BDS-1719 for continued review by @sghoweri and @mikemai2awesome

**Comment by EvanLovely** [comment]
Great feedback from @mikemai2awesome here: 
https://github.com/bolt-design-system/bolt/pull/1285#pullrequestreview-270943963

**Comment by mikemai2awesome** [comment]
@EvanLovely Thanks for replying to my feedback.

I am still trying to understand the one about `bolt-animate` inside an element instead of being a wrapper. Further explanation and demo would help. We can talk about it in the next sync up meeting.

```
<bolt-character
  characterUrl="https://github.com/basaltinc/temp-pega-dummy-assets/raw/master/animated-bands-ltr.png"
>
  <bolt-animate slot="top" idle="pulse">
  </bolt-animate>
  <bolt-animate slot="left" idle="pulse">
  </bolt-animate>
  <bolt-animate slot="right" idle="pulse">
  </bolt-animate>
  <bolt-animate slot="bottom" idle="pulse">
  </bolt-animate>
  <bolt-icon slot="icon" idle="none">
  </bolt-icon>
</bolt-character>
```

**Comment by EvanLovely** [comment]
@mikemai2awesome Sure thing! I'm happy to do a deeper dive in a technical demo with you next time!

**Pull request merged**
